config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'sleepings#index'
  resources :sleepings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sleeping.rb
class Sleeping < ApplicationRecord
  enum quality: {普通: "normal", 良: "good", 最高: "excellent", 悪い: "bad" }
  belongs_to :user
  def sleep_duration_minutes
    ((end_time - start_time) / 60).to_i
  end
  def sleep_duration
    (end_time - start_time) / 1.hour  
  end
  validates :quality, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  validates :email, uniqueness: true
  has_many :sleepings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/sleepings_controller.rb
class SleepingsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_sleep, only: [:show, :edit, :update, :destroy]
  def index
    @sleepings = Sleeping.all
    if @sleepings.present? 
      total_sleep_duration = @sleepings.sum { |sleeping| sleeping.sleep_duration.to_i }
      average_sleep_duration_minutes = total_sleep_duration / @sleepings.length
      @average_sleep_duration_hours = average_sleep_duration_minutes / 60
      @average_sleep_duration_minutes = average_sleep_duration_minutes % 60
    else
      @average_sleep_duration_hours = 0
      @average_sleep_duration_minutes = 0
    end
  end

  def show
  end

  def new
    @sleeping = Sleeping.new
  end

  def create
    @sleepings = Sleeping.new(sleep_params)
    if @sleeping.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @sleeping = Sleeping.find(params[:id])
    if sleep.update(sleep_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @sleeping = Sleeping.find(params[:id])
    @sleeping.destroy
    redirect_to root_path
  end

  private

  def set_sleep
    @Sleeping = Sleeping.find(params[:id])
  end

  def sleep_params
    params.require(:sleep).permit(:start_time, :end_time, :quality, :memo).merge(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_duration(seconds)
    hours = seconds / 3600
    minutes = (seconds % 3600) / 60
    seconds = seconds % 60
    "#{format('%02d', hours)}:#{format('%02d', minutes)}:#{format('%02d', seconds)}"
  end
end

app/helpers/sleepings_helper.rb
module SleepingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>sleep</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("sleep_man.png", class: :logo), root_path %>
            <h1 class="app-title">睡眠管理</h1>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "睡眠管理", new_sleeping_path, class: :nav__btn %>
              <%= link_to "リロード", "javascript:location.reload();", class: :nav__btn %>
              <%= link_to "トップページへ", root_path, class: :nav__btn %>
            </div> 
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              <%= link_to "リロード", "javascript:location.reload();", class: :nav__btn %>
              <%= link_to "トップページへ", root_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <%= link_to image_tag("hitsuji.png", class: :logo), root_path %>
      <%= link_to image_tag("animal_hitsuji_sleep.png", class: :logo), root_path %>
    </footer>
  </body>
</html>

app/views/sleepings/_form.html.erb
<%= form_with model: sleeping, local: true do |f|%>
  <div class="field">
    <%= f.label :start_time, "睡眠開始時間" %><br />
    <%= f.datetime_local_field :start_time, class: "form__text", id: "sleep_start_time" %>
  </div>

  <div class="field">
    <%= f.label :end_time, "睡眠終了時間" %><br />
    <%= f.datetime_local_field :end_time, class: "form__text", id: "sleep_end_time" %>
  </div>

  <div class="field">
    <%= f.label :quality, "睡眠の質" %><br />
    <%= f.select :quality, Sleeping.qualities.keys, class: "form__select", id: "sleep_quality" %>
  </div>

  <div class="field">
    <%= f.label :memo, "メモ" %><br />
    <%= f.text_area :memo, class: "form__text", id: "sleep_memo" %>
  </div>
  
  <div class="actions">
    <%= f.submit "保存する", class: "form__btn"  %>
  </div>
<% end %>

app/views/sleepings/_sleep.html.erb
<% @sleepings.each do |sleeping| %>
  <div class="sleep-record">
    <p><strong>睡眠開始時間:</strong> <%= sleeping.start_time %></p>
    <p><strong>睡眠終了時間:</strong> <%= sleeping.end_time %></p>
    <p><strong>睡眠の質:</strong> <%= sleeping.quality %></p>
    <p><strong>メモ:</strong> <%= sleeping.memo %></p>
    <%= link_to "詳細を見る", sleeping, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sleepings/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
     <h2>睡眠記録を編集</h2>
     <%= render partial: "form", locals: { sleep_m: @sleep_m } %>
     <%= link_to "一覧に戻る", sleeps_path, class: "btn btn-secondary" %>
    </div>
  </div>
</main>

app/views/sleepings/index.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "こんにちは、#{current_user.nickname} さん" %>
      </div> 
       <h2>平均睡眠時間: <%= @average_sleep_duration_minutes %>時間</h2>
    <% end %>
    <h2>睡眠記録一覧</h2>
    <div class="card__wrapper">
       <%= render partial: "sleep",locals: { sleeping: @sleepings }  %>
    </div>
  </div>
</main>

app/views/sleepings/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">睡眠記録記入</h2>
        <%= render partial: "form", locals: { sleeping: @sleeping } %>
    </div>
  </div>
</div>

app/views/sleepings/show.html.erb
<div class="sleep-details">
  <h2>睡眠記録詳細</h2>
  <p><strong>睡眠開始時間:</strong> <%= @sleeping.start_time %></p>
  <p><strong>睡眠終了時間:</strong> <%= @sleeping.end_time %></p>
  <p><strong>睡眠の質:</strong> <%= @sleeping.quality %></p>
  <p><strong>メモ:</strong> <%= @sleeping.memo %></p>
</div>

<%= link_to "編集", edit_sleeping_path(@sleeping), class: :prototype__btn %>
<%= link_to "戻る", sleepings_path, class: "btn btn-secondary" %>
<%= link_to "削除", sleeping_path(@sleeping.id), data: { turbo_method: :delete },class: :prototype__btn %>